### ISSUE TITLE
Trying to get angular 7 client to work against signalR asp.net core 2.2

### ISSUE THREAD

**Issue by foxjazz** [foxjazz/WebAdmsClient#1]
Trying to get angular 7 client to work against signalR asp.net core 2.2

The github client I am trying is located at:
https://github.com/foxjazz/WebAdmsClient

Server located at:
https://github.com/foxjazz/WebADMService.git

Error message:

`Access to XMLHttpRequest at 'https://localhost:5001/admchanges/negotiate' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
[2019-02-08T03:33:28.759Z] Warning: Error from HTTP request. 0: .
[2019-02-08T03:33:28.761Z] Error: Failed to complete negotiation with the server: Error
  push../node_modules/@aspnet/signalr/dist/esm/Utils.js.ConsoleLogger.log	
  (anonymous function)	
  step	
  (anonymous function)	
  rejected	
  push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke	
  onInvoke	
  push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke	
  push../node_modules/zone.js/dist/zone.js.Zone.run	
  (anonymous function)	
  push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask	
  onInvokeTask	
  push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask	
  push../node_modules/zone.js/dist/zone.js.Zone.runTask	
  drainMicroTaskQueue	
  push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask	
  invokeTask	
  globalZoneAwareCallback	
[2019-02-08T03:33:28.763Z] Error: Failed to start the connection: Error
  push../node_modules/@aspnet/signalr/dist/esm/Utils.js.ConsoleLogger.log	
  (anonymous function)	
  step	
  (anonymous function)	
  rejected	
  push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke	
  onInvoke	
  push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke	
  push../node_modules/zone.js/dist/zone.js.Zone.run	
  (anonymous function)	
  push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask	
  onInvokeTask	
  push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask	
  push../node_modules/zone.js/dist/zone.js.Zone.runTask	
  drainMicroTaskQueue	
  push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask	
  invokeTask	
  globalZoneAwareCallback	
Error while establishing connection :(Error
`

**Comment by bradygaster** [comment]
@brennanconroy, do you see anything in [the startup.cs code](https://github.com/foxjazz/WebADMService/blob/master/Startup.cs#L38-L65) that might be fixable from a CORS perspective? i'm working on something ATM that I can try these CORS settings out to see if I get the same thing.

**Comment by bradygaster** [comment]
After consulting with @brennanconroy i think this would be helpful. You need to allow credentials in your cors settings.https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.2#cross-origin-connections

**Comment by foxjazz** [comment]
Hi, so I understand what you are saying. And have done that with no change in result.
